### ISSUE TITLE
`wrapFetch()` doesn’t work with TypeScript without using `{}` as its first parameter

### ISSUE THREAD

**Issue by rojvv** [jd1378/deno-another-cookiejar#8]
Please either do update the README or make the first parameter optional.

**Comment by jd1378** [comment]
Thanks, readme was the expected way, fixed in v4.1.4 ([215f20a](https://github.com/jd1378/deno-another-cookiejar/commit/215f20a707bbf6c1bb69623d2fcea0101ae51b00))
