### ISSUE TITLE
CookieJar toString() method

### ISSUE THREAD

**Issue by Roosteridk** [jd1378/deno-another-cookiejar#9]
It would be nice to have a toString() method for the CookieJar class to use it when setting cookie header like `Cookie: name=value; name2=value2; name3=value3`

**Comment by jd1378** [comment]
Hi
you sure [`CookieJar.getCookieString`](https://github.com/jd1378/deno-another-cookiejar/blob/215f20a707bbf6c1bb69623d2fcea0101ae51b00/cookie_jar.ts#L194) does not do what you already want to do ?

**Comment by jd1378** [comment]
It's [what I currently use inside fetchWrapper](https://github.com/jd1378/deno-another-cookiejar/blob/215f20a707bbf6c1bb69623d2fcea0101ae51b00/fetch_wrapper.ts#L24)
edit: [Look here as well](https://github.com/jd1378/deno-another-cookiejar/blob/215f20a707bbf6c1bb69623d2fcea0101ae51b00/fetch_wrapper.ts#L38)

**Comment by Roosteridk** [comment]
Oh, my bad. Yes this is exactly what I was looking for. Thank you so much! Great module btw.

**Comment by Roosteridk** [comment]
#10 Added this PR so the method is easier to find 🔥

**Comment by jd1378** [comment]
released this in [v4.1.5](https://github.com/jd1378/deno-another-cookiejar/releases/tag/v4.1.5)
thanks for the PR
